---
- name: Install Application and Config Firewall
  hosts: summit-edu-{{ vm_name }}
  become: true
  tasks:

    - debug:
        msg: "{{ vm_application }}"

    - name: Install and Start Apache
      ansible.builtin.import_tasks: 
        file: deploy-webapp.yml
      when: vm_application == "apache"

    - name: Install and Start Cockpit
      ansible.builtin.import_tasks: 
        file: deploy-cockpit.yml
      when: vm_application == "cockpit"
