- name: Create Service Access the RHEL Web Console
  hosts: all
  tasks:

  - name: Create Cockpit Service
    kubernetes.core.k8s:
      state: present
      definition:
        apiVersion: v1
        kind: Service
        metadata:
          name: cockpit-testing-svc
          namespace: summit-edu
        spec:
          type: NodePort
          selector:
            env: cockpit-testing
          ports:
            - protocol: TCP
              port: 9090
              targetPort: 9090
    register: svc_info

  - name: Print Service Info
    debug:
      msg: "{{ svc_info }}"
  

