- name: Create Service Access the RHEL Web Console
  hosts: all
  tasks:

  - name: Create cockpit service
    kubernetes.core.k8s:
      state: present
      definition:
        apiVersion: v1
        kind: Service
        metadata:
          name: summit-edu-service
          namespace: summit-edu
        spec:
          type: NodePort
          selector:
            env: summit-edu
          ports:
            - protocol: TCP
              port: 9090
              targetPort: 9090

